/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hearts_Server.java
 *
 * Created on Jun 6, 2011, 11:20:25 AM
 */

package hearts_server;
import java.io.IOException;
import java.net.Socket;
import java.net.ServerSocket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Czytelnik
 */
public class Hearts_Server extends javax.swing.JFrame {

    /** Creates new form Hearts_Server */
    public Hearts_Server() {
        PortLangNghe=0;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextPortLangNghe = new javax.swing.JTextField();
        jButtonBatDau = new javax.swing.JButton();
        jButtonDong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(hearts_server.Hearts_ServerApp.class).getContext().getResourceMap(Hearts_Server.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextPortLangNghe.setFont(resourceMap.getFont("jtxtPortLangNghe.font")); // NOI18N
        jTextPortLangNghe.setText(resourceMap.getString("jtxtPortLangNghe.text")); // NOI18N
        jTextPortLangNghe.setName("jtxtPortLangNghe"); // NOI18N
        jTextPortLangNghe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPortLangNgheKeyPressed(evt);
            }
        });

        jButtonBatDau.setText(resourceMap.getString("jButtonBatDau.text")); // NOI18N
        jButtonBatDau.setName("jButtonBatDau"); // NOI18N
        jButtonBatDau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBatDauMouseClicked(evt);
            }
        });

        jButtonDong.setText(resourceMap.getString("jButtonDong.text")); // NOI18N
        jButtonDong.setName("jButtonDong"); // NOI18N
        jButtonDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonDongMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPortLangNghe, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBatDau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDong, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextPortLangNghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBatDau)
                    .addComponent(jButtonDong))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBatDauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBatDauMouseClicked
        // TODO add your handling code here:
        try {
            PortLangNghe = Integer.parseInt(jTextPortLangNghe.getText().trim());
            ServerS = new ServerSocket(PortLangNghe);
            jTextPortLangNghe.setEnabled(false);
            jButtonBatDau.setEnabled(false);
            ListenT = new ListenThread(ServerS);

        } catch (IOException ex) {
            Logger.getLogger(Hearts_Server.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Bạn nhập port có giá trị không hợp lệ");
        }


    }//GEN-LAST:event_jButtonBatDauMouseClicked

    private void jTextPortLangNgheKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPortLangNgheKeyPressed
        // TODO add your handling code here:
      if(evt.getKeyChar()<'0' || evt.getKeyChar()>'9')
          evt.setKeyChar('0');
    }//GEN-LAST:event_jTextPortLangNgheKeyPressed

    private void jButtonDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDongMouseClicked
    
            // TODO add your handling code here:
            //ListenT.Running = false;


    }//GEN-LAST:event_jButtonDongMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hearts_Server().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBatDau;
    private javax.swing.JButton jButtonDong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextPortLangNghe;
    // End of variables declaration//GEN-END:variables
    private Integer PortLangNghe;
    ServerSocket ServerS;
    ListenThread ListenT;

}
